Estados = {
  "aguascalientes": "Aguascalientes",
  "baja-california": "Baja California",
  "baja-california-sur": "Baja California Sur",
  "campeche": "Campeche",
  "coahuila-de-zaragoza": "Coahuila de Zaragoza",
  "colima": "Colima",
  "chiapas": "Chiapas",
  "chihuahua": "Chihuahua",
  "distrito-federal": "Distrito Federal",
  "durango": "Durango",
  "guanajuato": "Guanajuato",
  "guerrero": "Guerrero",
  "hidalgo": "Hidalgo",
  "jalisco": "Jalisco",
  "mexico": "México",
  "michoacan-de-ocampo": "Michoacan de Ocampo",
  "morelos": "Morelos",
  "nayarit": "Nayarit",
  "nuevo-leon": "Nuevo León",
  "oaxaca": "Oaxaca",
  "puebla": "Puebla",
  "queretaro": "Querétaro",
  "quintana-roo": "Quintana Roo",
  "san-luis-potosi": "San Luis Potosí",
  "sinaloa": "Sinaloa",
  "sonora": "Sonora",
  "tabasco": "Tabasco",
  "tamaulipas": "Tamaulipas",
  "tlaxcala": "Tlaxcala",
  "veracruz-de-ignacio-de-la-llave": "Veracruz de Ignacio de la Llave",
  "yucatan": "Yucatan",
  "zacatecas": "Zacatecas",
};
